version: '3'


services:
  postgres:
    image: postgres:16.1
    ports:
      - 5439:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # Test local run in docker
  # build app image with `make image` (also commented) beforehand

  # backend:
  #   image: test
  #   command: wait-for-it postgres:5432 -- /bin/sh -c "./manage.py migrate && uwsgi --master --http :8000 --module app.wsgi"
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - DATABASE_URL=postgres://postgres@postgres/postgres
  #   links:
  #     - postgres
